---
# Source: client-chart/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
spec:
  containers:
    - name: client
      image: localhost/client:v2
      imagePullPolicy: Never
