---
# Source: server-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
    name: server
    namespace: default
spec:
    selector:
      app: server
    ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
    type: LoadBalancer
---
# Source: server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: localhost/server:v2
          imagePullPolicy: Never
          name: server
          ports:
            - containerPort: 9001
              protocol: TCP
      restartPolicy: Always
