apiVersion: v1
kind: Service
metadata:
    name: server
    namespace: {{ .Values.namespace }}
spec:
    selector:
      app: server
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
    type: {{ .Values.service.type }}
